# Generated by Django 5.0.6 on 2026-05-16 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('document_id', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('resume_text', models.TextField(blank=True)),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('availability', models.CharField(choices=[('immediate', 'Inmediata'), ('two_weeks', '2 semanas'), ('one_month', '1 mes'), ('negotiable', 'A convenir')], default='negotiable', max_length=20)),
                ('current_position', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='CUIT/NIF')),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(choices=[('small', 'Pequena'), ('medium', 'Mediana'), ('large', 'Grande'), ('enterprise', 'Enterprise')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Tecnica'), ('soft', 'Soft'), ('education', 'Educacion')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIClassificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitosa'), ('failed', 'Fallida')], default='pending', max_length=20)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(default='v1', max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('tokens_prompt', models.PositiveIntegerField(default=0)),
                ('tokens_completion', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('education_level', models.CharField(choices=[('high_school', 'Secundario'), ('technical', 'Tecnico'), ('bachelor', 'Grado'), ('master', 'Maestria'), ('doctorate', 'Doctorado'), ('course', 'Curso'), ('certification', 'Certificacion')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-end_date', '-start_date', 'institution'],
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Tiempo completo'), ('part_time', 'Medio tiempo'), ('contractor', 'Contratista'), ('freelance', 'Freelance'), ('internship', 'Pasantia')], default='full_time', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('achievements', models.TextField(blank=True)),
                ('technologies', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-end_date', '-start_date', 'company'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('modality', models.CharField(choices=[('onsite', 'Presencial'), ('hybrid', 'Hibrida'), ('remote', 'Remota')], default='hybrid', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Abierta'), ('paused', 'Pausada'), ('closed', 'Cerrada')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closing_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='recruitment.organization')),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AIExtractedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('technical', 'Tecnica'), ('soft', 'Soft'), ('education', 'Educacion')], max_length=20)),
                ('evidence_text', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('classification_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_skills', to='recruitment.aiclassificationrun')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extracted_skills', to='recruitment.candidate')),
                ('normalized_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_extractions', to='recruitment.skill')),
            ],
            options={
                'ordering': ['category', '-confidence', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('applied', 'Postulado'), ('screening', 'Screening'), ('interview', 'Entrevista'), ('technical', 'Tecnica'), ('offer', 'Oferta'), ('hired', 'Contratado'), ('rejected', 'Rechazado')], default='applied', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('recruiter_notes', models.TextField(blank=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate')),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobopening')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'job_opening')},
            },
        ),
        migrations.CreateModel(
            name='JobSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('required', 'Excluyente'), ('important', 'Importante'), ('nice_to_have', 'Deseable')], max_length=20)),
                ('min_proficiency', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_mandatory', models.BooleanField(default=False)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='recruitment.jobopening')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='recruitment.skill')),
            ],
            options={
                'ordering': ['priority', 'skill__name'],
                'unique_together': {('job_opening', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('resume', 'CV'), ('ai', 'IA')], default='manual', max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('evidence_text', models.TextField(blank=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='recruitment.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='recruitment.skill')),
            ],
            options={
                'ordering': ['skill__category', 'skill__name'],
                'unique_together': {('candidate', 'skill', 'source')},
            },
        ),
    ]
