# Generated by Django 5.0.6 on 2026-05-18 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteTableSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_name', models.CharField(max_length=120, unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('is_selected', models.BooleanField(default=False)),
                ('last_remote_id', models.PositiveBigIntegerField(default=0)),
                ('records_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('idle', 'Inactiva'), ('success', 'Exitosa'), ('failed', 'Fallida')], default='idle', max_length=20)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['table_name'],
            },
        ),
        migrations.CreateModel(
            name='RemoteTableRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.PositiveBigIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='recruitment.remotetablesync')),
            ],
            options={
                'ordering': ['table__table_name', 'remote_id'],
                'unique_together': {('table', 'remote_id')},
            },
        ),
    ]
