# Generated by Django 5.0.6 on 2026-05-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_remotetablesync_remotetablerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idIntegration', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('source_system', models.CharField(default='ngovatek_hr', max_length=100)),
                ('formatted_cv_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alt_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('document_id', models.CharField(blank=True, max_length=50)),
                ('cuil', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('available_to_apply', models.BooleanField(default=True)),
                ('availability_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rejection_email_sent', models.BooleanField(default=False)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('health_insurance', models.CharField(blank=True, max_length=255)),
                ('bonuses', models.TextField(blank=True)),
                ('trainings', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('current_job', models.CharField(blank=True, max_length=255)),
                ('primary_profile', models.CharField(blank=True, max_length=255)),
                ('sub_profile', models.CharField(blank=True, max_length=255)),
                ('seniority', models.CharField(blank=True, max_length=255)),
                ('seniority_level', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('summary', models.TextField(blank=True)),
                ('technical_skills_text', models.TextField(blank=True)),
                ('languages_text', models.TextField(blank=True)),
                ('profile_description', models.TextField(blank=True)),
                ('skills_json', models.JSONField(blank=True, default=list)),
                ('languages_json', models.JSONField(blank=True, default=list)),
                ('education_json', models.JSONField(blank=True, default=list)),
                ('work_experience_json', models.JSONField(blank=True, default=list)),
                ('certifications_json', models.JSONField(blank=True, default=list)),
                ('integrated_payload', models.JSONField(blank=True, default=dict)),
                ('last_integrated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'integrationCandidates',
                'ordering': ['last_name', 'first_name', 'idIntegration'],
            },
        ),
    ]
