# Generated by Django 5.0.6 on 2026-05-18 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_integrationcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMAllowedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('technical', 'Tecnica'), ('soft', 'Soft'), ('education', 'Educacion'), ('language', 'Idiomas')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCandidateLLMRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitosa'), ('failed', 'Fallida')], default='pending', max_length=20)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(default='skills-v1', max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('request_prompt', models.TextField(blank=True)),
                ('allowed_skills_snapshot', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.TextField(blank=True)),
                ('normalized_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_runs', to='recruitment.integrationcandidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
