# Generated by Django 5.0.6 on 2026-05-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_llmallowedskill_integrationcandidatellmrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='educationSkills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='idIntegration',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='langSkills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='softSkills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='techSkills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
