# Generated by Django 5.0.6 on 2026-05-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidate_educationskills_candidate_idintegration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_s3_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='integrationcandidate',
            name='cv_s3_url',
            field=models.URLField(blank=True),
        ),
    ]
